layout_spectrum: 0.1404828
color:
  saturation: 0.7298604
  lightness: 0.7459721
  brandStrength: 1
  brandColors:
    - '#131314'
    - '#FB0102'
    - '#FFFC02'
    - '#42B403'
    - '#FBFCF2'
  rhythmicContrast: 0.3700322
typography_spectrum: 0.6278195
name: kcarnes
